### ISSUE TITLE
remove alexa

### ISSUE THREAD

**Issue by muamua33** [DistriNet/tranco-list#19]
![Screenshot_2023-04-21-04-16-29-727_com android chrome-edit](https://user-images.githubusercontent.com/111419642/233478437-77f989a1-00c4-4154-868c-762fb94e3145.jpg)

the alexa ranking has become unavailable since 01-feb-2023

**Comment by VictorLeP** [comment]
We are aware that the Alexa list has stopped updating since 1 February (though the file is currently still available, unlike the archive page you show).
We'll update Tranco in due course to remove Alexa.

**Comment by Seirdy** [comment]
Cloudflare Radar is another source. SimilarWeb has its own ranking but I've found its quality to be questionable.

**Comment by VictorLeP** [comment]
From August 1, we'll remove Alexa and add the Chrome User Experience Report and Cloudflare Radar.
(The SimilarWeb list requires a subscription AFAICT.)

**Comment by Seirdy** [comment]
The problem with CrUX is that it measures engagement rather than prominence. A few users visiting a website a lot will inflate its ranking, as will many users visiting a website infrequently but regularly. It's biased towards websites that people open often rather than websites that people share and reference.

There's merit to the approach, but I'm not sure how well it combines with other rankings because its approach is so fundamentally different. CrUX feels like more of an alternative to Tranco than a source for it. I suggest sticking with Radar for now, and observing interesting differences between the resulting Tranco list and CrUX's alternative approach.

-- 
Seirdy (https://seirdy.one)

**Comment by VictorLeP** [comment]
Thanks for the insight! Do you maybe have additional resources that show how CrUX measures engagement specifically? For example, for the [CrUX docs](https://developer.chrome.com/docs/crux/methodology/#popularity-eligibility), I actually interpret CrUX as counting visitors, which would exclude the 'few users visiting a website a lot' scenario.
CrUX has also been considered as [the most accurate top list](https://kcruth.com/papers/2022-Toplists.pdf) when compared to Cloudflare HTTP traffic, by the way.
Also, I'd consider Radar/Umbrella/Farsight to definitely also reflect engagement (in terms of DNS queries) - only Majestic would be more on the 'share/reference' side.

In the end, everything also depends on how you define 'popular': maybe some people actually want it to reflect traffic (opening a page) rather than prominence (referencing, sharing, ...)

There is of course also always the option to build your custom list that excludes CrUX :)
