### ISSUE TITLE
Part of the List is Alphabetically-Sorted

### ISSUE THREAD

**Issue by zifeng-kang** [DistriNet/tranco-list#22]
Hi Tranco authors, 

Thanks for this convenient tool. I would like to understand why part of the list is alphabetically sorted. Is there a bug in your source code? 

E.g.: In tranco_LJ494.csv

769101,a25.com
769102,a4h-tech.com
769103,aarthiscan.com
769104,abcatering.dk
769105,abcrestaurants.com
769106,abelharainha.com.br
769107,abiturients.info
769108,abrahadabra.pl
769109,abulkhairgroup.com
769110,academie-educ.com
769111,acharei.com.br
769112,acilcalisanlari.com
769113,actec-solar.de
...
771120,zofti.com
771121,zonacristiana.org
771122,zoombook.lt
771123,zoonews.pl
771124,zznet.com.br

**Comment by VictorLeP** [comment]
The existence of alphabetically sorted clusters is a fairly well-known characteristic of top lists, see for example [this paper from 2019](https://seclab.nu/static/publications/pam2019.pdf) (section 3.3).

Concretely for Tranco, the domains in such a cluster have an identical score after aggregating across rankings, e.g., because they only appear in CrUX. Afterwards, they are sorted alphabetically on purpose, as there is no definitive way of distinguishing them otherwise. We're looking into the effects this has on the list and the analyses based on it, but for now this behavior will persist.

**Comment by zifeng-kang** [comment]
Thank you very much for the information!
